name: Build React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        run: |
          git clone https://<username>:<password>@github.com/<username>/<repository>.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
